# Generated by Django 5.1.6 on 2025-03-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDanhMuc', models.AutoField(primary_key=True, serialize=False)),
                ('TenDanhMuc', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DongSanPham',
            fields=[
                ('MaDongSanPham', models.AutoField(primary_key=True, serialize=False)),
                ('TenDongSanPham', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('MaThuongHieu', models.AutoField(primary_key=True, serialize=False)),
                ('TenThuongHieu', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSanPham', models.AutoField(primary_key=True, serialize=False)),
                ('TenSanPham', models.CharField(max_length=100)),
                ('MoTa', models.TextField()),
                ('SoLuongKho', models.IntegerField(default=0)),
                ('TrangThai', models.CharField(max_length=20)),
                ('DongSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.dongsanpham')),
                ('MaDanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.danhmuc')),
            ],
        ),
        migrations.AddField(
            model_name='dongsanpham',
            name='ThuongHieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.thuonghieu'),
        ),
    ]
