# Generated by Django 5.1.6 on 2025-03-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungLuong',
            fields=[
                ('MaDungLuong', models.AutoField(primary_key=True, serialize=False)),
                ('DungLuong', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MauSac',
            fields=[
                ('MaMauSac', models.AutoField(primary_key=True, serialize=False)),
                ('TenMauSac', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('MaHinhAnh', models.AutoField(primary_key=True, serialize=False)),
                ('LinkAnhSanPham', models.URLField(max_length=150)),
                ('MaSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.sanpham')),
                ('MaMauSac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.mausac')),
            ],
        ),
        migrations.CreateModel(
            name='GiaSanPham',
            fields=[
                ('MaGiaSanPham', models.AutoField(primary_key=True, serialize=False)),
                ('GiaSanPham', models.FloatField()),
                ('MaDungLuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.dungluong')),
                ('MaSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.sanpham')),
                ('MaMauSac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.mausac')),
            ],
        ),
    ]
