# Generated by Django 5.1.6 on 2025-03-09 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0005_alter_hinhanhsanpham_linkanhsanpham'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHang',
            fields=[
                ('MaDatHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('LoiNhan', models.TextField(blank=True, null=True)),
                ('TenSanPham', models.CharField(max_length=100)),
                ('GiaSanPham', models.FloatField()),
                ('MaDungLuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.dungluong')),
                ('MaMauSac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.mausac')),
                ('MaSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.sanpham')),
            ],
        ),
    ]
