# Generated by Django 5.1.6 on 2025-03-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0006_dathang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathang',
            name='MaDungLuong',
        ),
        migrations.RemoveField(
            model_name='dathang',
            name='MaMauSac',
        ),
        migrations.RemoveField(
            model_name='dathang',
            name='MaSanPham',
        ),
        migrations.RemoveField(
            model_name='dathang',
            name='TenSanPham',
        ),
        migrations.AlterField(
            model_name='dathang',
            name='GiaSanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.giasanpham'),
        ),
        migrations.AlterField(
            model_name='dathang',
            name='TenKhachHang',
            field=models.CharField(max_length=255),
        ),
    ]
