# Generated by Django 5.1.6 on 2025-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0007_remove_dathang_madungluong_remove_dathang_mamausac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dathang',
            name='GiaSanPham',
        ),
        migrations.AddField(
            model_name='dathang',
            name='MaSP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dathang',
            name='TenKhachHang',
            field=models.CharField(max_length=100),
        ),
    ]
