# Generated by Django 5.1.6 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0008_remove_dathang_giasanpham_dathang_masp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhKhachHang',
            fields=[
                ('MaAnhKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('LinkAnhKhachHang', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
