# Generated by Django 5.1.6 on 2025-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0009_anhkhachhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dathang',
            name='TrangThai',
            field=models.CharField(default='Chờ liên hệ', max_length=50),
        ),
    ]
