# Generated by Django 5.1.6 on 2025-03-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0010_dathang_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='dathang',
            name='NguoiLienHe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
