# Generated by Django 5.1.6 on 2025-03-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0011_dathang_nguoilienhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongsanpham',
            name='DanhMuc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appBanDT.danhmuc'),
        ),
    ]
