# Generated by Django 5.1.6 on 2025-03-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0012_dongsanpham_danhmuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongSoKyThuat',
            fields=[
                ('MaThongSo', models.AutoField(primary_key=True, serialize=False)),
                ('ManHinh', models.CharField(blank=True, max_length=255, null=True)),
                ('HeDieuHanh', models.CharField(blank=True, max_length=50, null=True)),
                ('CPU', models.CharField(blank=True, max_length=100, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('BoNhoTrong', models.CharField(blank=True, max_length=50, null=True)),
                ('CameraTruoc', models.CharField(blank=True, max_length=50, null=True)),
                ('CameraSau', models.CharField(blank=True, max_length=100, null=True)),
                ('TheSIM', models.CharField(blank=True, max_length=100, null=True)),
                ('DungLuongPin', models.CharField(blank=True, max_length=100, null=True)),
                ('CongKetNoi', models.CharField(blank=True, max_length=255, null=True)),
                ('TrongLuong', models.CharField(blank=True, max_length=50, null=True)),
                ('ChongNuoc', models.BooleanField(default=False)),
                ('TinhNangDacBiet', models.TextField(blank=True, null=True)),
                ('SanPham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appBanDT.sanpham')),
            ],
        ),
    ]
