# Generated by Django 5.1.6 on 2025-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanDT', '0013_thongsokythuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongsokythuat',
            name='ChongNuoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thongsokythuat',
            name='CongKetNoi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thongsokythuat',
            name='ManHinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
